[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-wallhaven-6kx9kq_1680x1050
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-wallhaven-6kx9kq_1680x1050
GtkTheme=oomox-wallhaven-6kx9kq_1680x1050
IconTheme=oomox-wallhaven-6kx9kq_1680x1050
MetacityTheme=oomox-wallhaven-6kx9kq_1680x1050
